---
# Continuous Integration Workflow: Test case suite run + validation build check
name: CI

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # Job: Unit test suite
  unit-tests:
    name: "Unit Tests"
    runs-on: ubuntu-latest
    steps:
      # Install Multilib
      - name: Install Multilib
        run: |
          sudo apt-get update --assume-yes
          sudo apt-get install --assume-yes --quiet gcc-multilib

      # Checks out repository under $GITHUB_WORKSPACE
      - name: Checkout Latest Repo
        uses: actions/checkout@v2
        with: 
          submodules: recursive

      # Install Ruby Testing Tools
      - name: Setup Ruby Testing Tools
        run: |
          sudo gem install bundler
          sudo gem install rspec
          sudo gem install rubocop -v 0.57.2
          bundle install

      # Run Tests
      - name: Run All Unit Tests
        run: |
          cd test && rake ci
